version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: weekly
      day: monday
    groups:
      backend-npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: terraform
    directory: "/infra"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: terraform
    directory: "/infra/bootstrap"
    schedule:
      interval: weekly
      day: monday
